FROM golang:1.16.3-stretch AS builder
LABEL AUTHOR TACO Team (taco.sktelecom@gmail.com)

RUN mkdir -p /build
WORKDIR /build

COPY . .
RUN go mod tidy && go mod vendor
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/ep2tks ./cmd/register_endpoint.go

RUN mkdir -p /dist
WORKDIR /dist
RUN cp /build/bin/ep2tks ./ep2tks

FROM golang:alpine3.13

RUN mkdir -p /app
WORKDIR /app

COPY --chown=0:0 --from=builder /dist /app/
EXPOSE 9111

ENTRYPOINT ["/app/ep2tks"]
CMD ["-h"]
